--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vecnavium/VecnaStats
build-by-default: true
branches:
- PM4
projects:
  VecnaStats:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/libFormAPI
        version: 1.4.0-alpha
...
